baseURL = "http://handmade.iptime.org/"
languageCode = "en-us"
title = "HANDMADE LOG"
theme = "ezhil"

hasCJKLanguage = true

# Enable syntax highlighting.
#pygmentsstyle = "vs"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentscodefencesguesssyntax = true

# Your Google analytics code.
#googleAnalytics = "UA-123-45"
# Your Disqus sortname.
disqusShortname = "handmade-iptime-org"

[params]
	# Blog subtitle which appears below blog title. Supports markdown.
	subtitle = "Life is Strange"
	# Number of posts to show in recent posts list (Optional). Defaults to 10.
	recentPostsCount = 10
	# Content types which are excluded from recent posts and archive page (Optional). Defaults to ["page"]
	excludedTypes = ["page"]
	# Content types which are excludes Disqus comments (Optional). Defaults to ["page"]
	disableDisqusTypes = ["page"]
	# If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
	featherIconsCDN = true
	rss = true

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts/"
weight = 2

[[menu.main]]
name = "About"
url = "/page/about/"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).
[[params.social]]
name = "Repogitory"
icon = "gitlab"
url = "https://www.enjian.ml"

#[[params.social]]
#name = "Twitter"
#icon = "twitter"
#url = "https://twitter.com/gohugoio"

# Enable tags.
[taxonomies]
   tag = "tags"
