baseURL = "http://handmade.iptime.org/"
title = "HANDMADE LOG"

languageCode = "en-us"
DefaultContentLanguage="en"

theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

# googleAnalytics = ""
# disqusShortname = ""

#archetypeDir = "archetypes"
#contentDir   = "content"
#dataDir      = "data"
#layoutDir    = "layouts"
publishDir   = "public"

hasCJKLanguage = true

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Enji"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = ""

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Homepage and blog by Enji"
  keywords = "homepage, blog, informatics, development, programming"
  images = [""]

  homeSubtitle = "Life is Strange"

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = ""

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = []
  customJS  = []

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = false  # Set "text-align: justify" to .content.

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"
  themeColor = "#252627"

[params.logo]
  logoText = "$ cd /home"
  logoHomeLink = "/"

[[params.social]]
  name = "gitlab"
  url  = "https://www.enjian.ml/"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/page/about"
  [[menu.main]]
    identifier = "Posts"
    name = "Posts"
    url = "/posts"

[languages]
  [languages.en]
#    title = "HANDMADE LOG"
    subtitle = "Life is Strange"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"


    #[languages.en.params.logo]
    #  logoText = "$ cd /home"
    #  logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

#	# You can create a language based menu
#    [languages.en.menu]
#      [[languages.en.menu.main]]
#        identifier = "about"
#        name = "About"
#        url = "/page/about"
#      [[languages.en.menu.main]]
#        identifier = "Posts"
#        name = "Posts"
#        url = "/posts"


